### ISSUE TITLE
Não está funcionando

### ISSUE THREAD

**Issue by ferfelipetto** [jptiberio/GravityForms-Valida-CPF-CNPJ#1]
Amigão, parabéns pelo plugin, é algo realmente indispensável para os sites brasileiros. Porém instalei em dois sites meus e não consegui fazer funcionar.
Pode me ajudar?

**Comment by jtiberio-sv** [comment]
Olá Felipe, 
Muito obrigado, posso ajudar sim.
Após instalar o plugin, acesse o seu formulário e no input que deseja adicionar a validação, edite-o e na aba "Aparência" adicione essa classe aqui "cpf_cnpj".
Veja se deu certo e me avise.

Abraços.

**Comment by ferfelipetto** [comment]
Obrigadão pela rápida resposta :)

Então, eu fiz isso, mas mesmo assim não funciona: http://prntscr.com/ncd7z4

Está aceitando quaisquer números, tipo 111.111.111-11
